package com.test.demo.model;

import java.util.Date;

public class SysView {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_view.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_view.ip
     *
     * @mbggenerated
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_view.create_by
     *
     * @mbggenerated
     */
    private Date createBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_view.id
     *
     * @return the value of sys_view.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_view.id
     *
     * @param id the value for sys_view.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_view.ip
     *
     * @return the value of sys_view.ip
     *
     * @mbggenerated
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_view.ip
     *
     * @param ip the value for sys_view.ip
     *
     * @mbggenerated
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_view.create_by
     *
     * @return the value of sys_view.create_by
     *
     * @mbggenerated
     */
    public Date getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_view.create_by
     *
     * @param createBy the value for sys_view.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(Date createBy) {
        this.createBy = createBy;
    }
}