spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.14.191.112:3307/MyBlog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 514root

server:
  port: 8636
  tomcat:
    uri-encoding: utf-8



#logger
logging:
  file:
    max-size: 10MB
  level:
    root: info


# map-underscore-to-camel-case-case 驼峰转换
mybatis:
  mapper-locations: classpath:com/test/demo/dao/basexml/*.xml
  type-aliases-package: com.test.demo.model
  configuration:
    map-underscore-to-camel-case: true

