package com.test.demo.dao.java;

import com.test.demo.model.SysLog;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface SysLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated
     */
    int insert(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated
     */
    List<SysLog> selectAll();

    @Select("select * from sys_log;")
    List<SysLog> getAll();

    List<SysLog> all();

    @Select("SELECT * FROM sys_log\n" +
            "ORDER BY id DESC LIMIT ${num}")
    List<SysLog> accessLog(Integer num);
}