package com.test.demo.dao.java;

import com.test.demo.model.SysLog;
import org.apache.ibatis.annotations.Select;
import org.apache.log4j.net.SyslogAppender;

import java.util.List;

public interface SysLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Wed Mar 13 17:27:34 CST 2019
     */
    int insert(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_log
     *
     * @mbggenerated Wed Mar 13 17:27:34 CST 2019
     */
    List<SysLog> selectAll();

    @Select("select * from sys_log;")
    List<SysLog> getAll();

    List<SysLog> all();
}