package com.test.demo.dao.java;

import com.test.demo.model.SysView;
import java.util.List;

public interface SysViewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_view
     *
     * @mbggenerated Thu Mar 14 17:33:02 CST 2019
     */
    int insert(SysView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_view
     *
     * @mbggenerated Thu Mar 14 17:33:02 CST 2019
     */
    List<SysView> selectAll();
}