package com.test.demo.dao.java;

import com.test.demo.model.TblArticleContent;
import java.util.List;

public interface TblArticleContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_content
     *
     * @mbggenerated Wed Mar 13 17:27:34 CST 2019
     */
    int insert(TblArticleContent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_article_content
     *
     * @mbggenerated Wed Mar 13 17:27:34 CST 2019
     */
    List<TblArticleContent> selectAll();
}