package com.test.demo.dao.java;

import com.test.demo.model.TblMessage;
import java.util.List;

public interface TblMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_message
     *
     * @mbggenerated Wed Mar 13 17:27:34 CST 2019
     */
    int insert(TblMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_message
     *
     * @mbggenerated Wed Mar 13 17:27:34 CST 2019
     */
    List<TblMessage> selectAll();
}