package com.test.demo.dao.java;

import com.test.demo.model.UserInfo;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbggenerated
     */
    List<UserInfo> selectAll();

    @Select("select * from user_info where id = #{id} and password = #{password};")
    List<UserInfo> selectUsers(@Param("id") Integer id,@Param("password") String password);
}